# Generated by Django 3.2.8 on 2021-12-24 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profesor', '0001_initial'),
        ('administrativo', '0001_initial'),
        ('inscripcion', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('externo', models.BooleanField(default=True, verbose_name='Perfil Externo')),
                ('inscripcionprincipal', models.BooleanField(default=False, verbose_name='Inscripción principal')),
                ('administrativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administrativo.administrativo', verbose_name='Administrativo')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscripcion.inscripcion', verbose_name='Inscripción')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profesor.profesor', verbose_name='Profesor')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['persona', 'inscripcion', 'administrativo', 'profesor', 'externo'],
                'unique_together': {('persona', 'inscripcion', 'administrativo', 'profesor', 'externo')},
            },
        ),
    ]
