# Generated by Django 3.2.8 on 2021-12-24 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0001_initial'),
        ('paralelo', '0001_initial'),
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='Fecha de inscripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumno.alumno', verbose_name='Persona')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.cursoparalelo', verbose_name='Curso')),
                ('paralelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paralelo.paralelo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción de alumno',
                'verbose_name_plural': 'Inscripciones de alumnos',
                'ordering': ['alumno', '-fecha', 'curso'],
                'unique_together': {('alumno', 'curso')},
            },
        ),
    ]
