# Generated by Django 3.2.8 on 2021-12-24 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.CharField(default='', max_length=2, verbose_name='Grupo')),
                ('rh', models.IntegerField(choices=[(1, '+'), (2, '-')], default=1, verbose_name='RH')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Sangre',
                'verbose_name_plural': 'Tipos de Sangre',
                'ordering': ['grupo'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('apellido1', models.CharField(default='', max_length=50, verbose_name='1er Apellido')),
                ('apellido2', models.CharField(default='', max_length=50, verbose_name='2do Apellido')),
                ('cedula', models.CharField(blank=True, default='', max_length=20, verbose_name='Cedula')),
                ('pasaporte', models.CharField(blank=True, default='', max_length=20, verbose_name='Pasaporte')),
                ('ruc', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Ruc')),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento o constitución')),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Transgenero'), (4, 'Neutro'), (5, 'Sin genero')], default=1)),
                ('sector', models.CharField(default='', max_length=300, verbose_name='Sector de residencia')),
                ('direccion', models.CharField(default='', max_length=300, verbose_name='Calle principal')),
                ('direccion2', models.CharField(default='', max_length=300, verbose_name='Calle secundaria')),
                ('num_direccion', models.CharField(default='', max_length=15, verbose_name='Numero')),
                ('referencia', models.CharField(default='', max_length=300, verbose_name='Referencia')),
                ('telefono', models.CharField(default='', max_length=50, verbose_name='Telefono movil')),
                ('telefono_conv', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Telefono fijo')),
                ('email', models.CharField(default='', max_length=200, verbose_name='Correo electronico personal')),
                ('emailinst', models.CharField(default='', max_length=200, verbose_name='Correo electronico institucional')),
                ('libretamilitar', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Libreta militar')),
                ('lgtbi', models.BooleanField(default=False, verbose_name='LGTBI')),
                ('datosactualizados', models.IntegerField(default=0, verbose_name='Datos Actualizados')),
                ('lugarecidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.parroquia', verbose_name='Lugar de residencia')),
                ('lugarnacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.parroquia', verbose_name='Lugar de nacimiento')),
                ('sangre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.tiposangre', verbose_name='Tipo de Sangre')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personal',
                'ordering': ['apellido1', 'apellido2', 'nombres'],
                'unique_together': {('cedula', 'ruc', 'pasaporte')},
            },
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.provincia', verbose_name='Provincia')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canton',
                'verbose_name_plural': 'Cantones',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'provincia')},
            },
        ),
    ]
