# Generated by Django 3.2.8 on 2021-12-24 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
        ('producto', '0001_initial'),
        ('matricula', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha emisión')),
                ('fechavence', models.DateField(verbose_name='Fecha vencimiento')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor')),
                ('valoriva', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor IVA')),
                ('valortotal', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor total')),
                ('valordescuento', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor descuento')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Saldo')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('observacion', models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Observación')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulados')),
                ('bloqueado', models.BooleanField(default=False)),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa', verbose_name='IVA')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matricula.matricula', verbose_name='Matricula')),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.pension', verbose_name='Pension')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona', verbose_name='Cliente')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.inventario', verbose_name='Producto')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rubro de cobro',
                'verbose_name_plural': 'Rubros de cobro',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('subtotal0', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor')),
                ('subtotaliva', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='IVA')),
                ('valordescuento', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Total')),
                ('valortotal', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Total')),
                ('efectivo', models.BooleanField(default=True, verbose_name='Pago en efectivo')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rubro.rubro', verbose_name='Rubros')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha'],
            },
        ),
    ]
