# Generated by Django 3.2.8 on 2022-01-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha emisión'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='fechavence',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
    ]
