# Generated by Django 3.2.8 on 2022-01-12 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_auto_20220112_1152'),
        ('rubro', '0002_auto_20220112_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='pension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matricula.pension', verbose_name='Pension'),
        ),
    ]
