# Generated by Django 3.2.8 on 2022-01-23 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_valor'),
        ('rubro', '0005_alter_rubro_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto', verbose_name='Producto'),
        ),
    ]
