# Generated by Django 3.2.8 on 2022-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_modeloparcial_notascurso_quimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimestre',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
