# Generated by Django 3.2.8 on 2022-01-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
        ('curso', '0003_quimestre_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='notascurso',
            name='parcial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curso.modeloparcial', verbose_name='Quimestre y Parcial'),
        ),
        migrations.AlterField(
            model_name='notascurso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripcion.inscripcion', verbose_name='Inscripcion de Alumno'),
        ),
        migrations.AlterField(
            model_name='notascurso',
            name='cursoasignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.materiaasignada', verbose_name='Curso y Materia'),
        ),
    ]
