# Generated by Django 3.2.8 on 2022-01-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripcion', '0001_initial'),
        ('curso', '0004_auto_20220125_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoQuimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('cursoasignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.materiaasignada', verbose_name='Curso y Materia')),
                ('parcial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curso.modeloparcial', verbose_name='Quimestre y Parcial')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotasAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Nota')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripcion.inscripcion', verbose_name='Inscripcion de Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.cursoquimestre', verbose_name='Curso Quimestre parcial')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cursoparalelo',
            name='parciales',
            field=models.IntegerField(default=0, verbose_name='Numero de Parciales'),
        ),
        migrations.AddField(
            model_name='cursoparalelo',
            name='quimestres',
            field=models.IntegerField(default=0, verbose_name='Numero de Quimestres'),
        ),
        migrations.DeleteModel(
            name='NotasCurso',
        ),
    ]
