# Generated by Django 3.2.8 on 2022-01-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20220125_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalumno',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nota'),
        ),
    ]
