# Generated by Django 3.2.8 on 2022-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_alter_notasalumno_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoquimestre',
            name='actacerrada',
            field=models.BooleanField(default=False),
        ),
    ]
