# Generated by Django 3.2.8 on 2021-12-24 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='Fecha pension')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pension',
                'verbose_name_plural': 'Pensiones',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('becado', models.BooleanField(default=False, verbose_name='Becado')),
                ('porcientobeca', models.FloatField(default=0, verbose_name='% de Beca')),
                ('observaciones', models.TextField(default='', max_length=1000, verbose_name='Observaciones')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fechatope', models.DateField(blank=True, null=True, verbose_name='Fecha límite de cancelación')),
                ('cerrada', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripcion.inscripcion', verbose_name='Inscripción')),
                ('pensiones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matricula.pension', verbose_name='pensiones')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'unique_together': {('inscripcion',)},
            },
        ),
    ]
