# Generated by Django 3.2.8 on 2022-01-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_auto_20220112_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pension',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha pension'),
        ),
        migrations.AlterField(
            model_name='pension',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='pension',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
        ),
    ]
