# Generated by Django 3.2.8 on 2022-01-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodolectivo',
            name='inicioactividades',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de incio de actividades academicas'),
        ),
    ]
