# Generated by Django 3.2.8 on 2021-12-24 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
        ('rubro', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('numero', models.IntegerField(default=0, verbose_name='Numero')),
                ('numerocompleto', models.CharField(default='', max_length=20, verbose_name='Numero Completo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observacion', models.TextField(blank=True, default='', null=True, verbose_name='Observación')),
                ('valida', models.BooleanField(default=True, verbose_name='Valida')),
                ('subtotal_base_iva', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('subtotal_base0', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('impresa', models.BooleanField(default=False, verbose_name='Impresa')),
                ('identificacion', models.CharField(default='', max_length=20, verbose_name='Identificación')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('direccion', models.TextField(default='', verbose_name='Dirección')),
                ('telefono', models.CharField(default='', max_length=50, verbose_name='Telefono')),
                ('electronica', models.BooleanField(default=False, verbose_name='Electrónica')),
                ('pagada', models.BooleanField(default=True, verbose_name='Pagada')),
                ('estado', models.IntegerField(choices=[(1, 'CORRECTA'), (2, 'INCORRECTA'), (3, 'ANULADA')], default=1, verbose_name='Estado Factura')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona', verbose_name='Cliente')),
                ('ivaaplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.iva', verbose_name='Iva Aplicado')),
                ('pagos', models.ManyToManyField(blank=True, to='rubro.Pago', verbose_name='Pagos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['numero'],
                'unique_together': {('numero',)},
            },
        ),
    ]
