# Generated by Django 3.2.8 on 2022-01-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_alter_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(3, 'ANULADA'), (2, 'INCORRECTA'), (1, 'CORRECTA')], default=1, verbose_name='Estado Factura'),
        ),
    ]
