# Generated by Django 3.2.8 on 2022-01-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_alter_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(2, 'INCORRECTA'), (1, 'CORRECTA'), (3, 'ANULADA')], default=1, verbose_name='Estado Factura'),
        ),
    ]
