# Generated by Django 3.2.8 on 2022-01-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0010_alter_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='boucher',
            field=models.TextField(default='', verbose_name='Numero de Boucher'),
        ),
        migrations.AddField(
            model_name='factura',
            name='formapago',
            field=models.IntegerField(choices=[(2, 'TRANSFERENCIA'), (1, 'EFECTIVO'), (3, 'DEPOSITO'), (4, 'TARJETA DE CREDITO/DEBITO')], default=1, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='referencia_deposito',
            field=models.TextField(default='', verbose_name='Referencia deposito'),
        ),
        migrations.AddField(
            model_name='factura',
            name='referencia_trasnferencia',
            field=models.TextField(default='', verbose_name='Referencia deposito'),
        ),
        migrations.AddField(
            model_name='factura',
            name='verificada',
            field=models.BooleanField(default=False, verbose_name='Verificada'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(1, 'CORRECTA'), (2, 'INCORRECTA'), (3, 'ANULADA')], default=1, verbose_name='Estado Factura'),
        ),
    ]
