# Generated by Django 3.2.8 on 2022-01-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0012_auto_20220122_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='referencia_trasnferencia',
            new_name='referencia_transferencia',
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(1, 'CORRECTA'), (3, 'ANULADA'), (2, 'INCORRECTA')], default=1, verbose_name='Estado Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='formapago',
            field=models.IntegerField(choices=[(2, 'TRANSFERENCIA'), (1, 'EFECTIVO'), (3, 'DEPOSITO'), (4, 'TARJETA DE CREDITO/DEBITO')], default=1, verbose_name='Forma de pago'),
        ),
    ]
