# Generated by Django 3.2.8 on 2022-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0013_auto_20220122_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='boucher',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Numero de Boucher'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(3, 'ANULADA'), (1, 'CORRECTA'), (2, 'INCORRECTA')], default=1, verbose_name='Estado Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='formapago',
            field=models.IntegerField(choices=[(3, 'DEPOSITO'), (2, 'TRANSFERENCIA'), (1, 'EFECTIVO'), (4, 'TARJETA DE CREDITO/DEBITO')], default=1, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='referencia_deposito',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Referencia deposito'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='referencia_transferencia',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Referencia deposito'),
        ),
    ]
