# Generated by Django 3.2.8 on 2022-01-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0017_auto_20220125_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(1, 'CORRECTA'), (3, 'ANULADA'), (2, 'INCORRECTA')], default=1, verbose_name='Estado Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='formapago',
            field=models.IntegerField(choices=[(4, 'TARJETA DE CREDITO/DEBITO'), (1, 'EFECTIVO'), (3, 'DEPOSITO'), (2, 'TRANSFERENCIA')], default=1, verbose_name='Forma de pago'),
        ),
    ]
