# Generated by Django 3.2.8 on 2022-01-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0019_auto_20220125_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formapago',
            field=models.IntegerField(choices=[(4, 'TARJETA DE CREDITO/DEBITO'), (2, 'TRANSFERENCIA'), (3, 'DEPOSITO'), (1, 'EFECTIVO')], default=1, verbose_name='Forma de pago'),
        ),
    ]
