# Generated by Django 3.2.8 on 2022-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0020_alter_factura_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(2, 'INCORRECTA'), (1, 'CORRECTA'), (3, 'ANULADA')], default=1, verbose_name='Estado Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='formapago',
            field=models.IntegerField(choices=[(3, 'DEPOSITO'), (2, 'TRANSFERENCIA'), (4, 'TARJETA DE CREDITO/DEBITO'), (1, 'EFECTIVO')], default=1, verbose_name='Forma de pago'),
        ),
    ]
