# Generated by Django 3.2.8 on 2022-01-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0023_auto_20220128_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(1, 'CORRECTA'), (3, 'ANULADA'), (2, 'INCORRECTA')], default=1, verbose_name='Estado Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='formapago',
            field=models.IntegerField(choices=[(2, 'TRANSFERENCIA'), (4, 'TARJETA DE CREDITO/DEBITO'), (3, 'DEPOSITO'), (1, 'EFECTIVO')], default=1, verbose_name='Forma de pago'),
        ),
    ]
