# Generated by Django 3.2.8 on 2022-01-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_grupomodulo_peril'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupomodulo',
            name='peril',
        ),
    ]
