# Generated by Django 3.2.8 on 2022-01-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Ruc'),
        ),
    ]
