# Generated by Django 3.2.8 on 2022-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcioncorta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion corta'),
        ),
    ]
